"""empty message

Revision ID: e6112c69251f
Revises: 80d38cad8383
Create Date: 2020-09-08 19:14:25.376004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6112c69251f'
down_revision = '80d38cad8383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('hide', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'hide')
    # ### end Alembic commands ###
